services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: fastapi_rag_backend:latest
    container_name: fastapi_rag_backend
    restart: unless-stopped
    env_file:
      - backend/.env
    environment:
      DATABASE_URL: postgresql://rag_user:rag_password@db:5432/rag_db
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend

  db:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    image: fastapi_rag_postgres:17
    container_name: fastapi_rag_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_password
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
