"""create files table

Revision ID: 4f0c8ffcd0cc
Revises: 
Create Date: 2026-05-26 02:48:00.726723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0c8ffcd0cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_texts_id'), table_name='texts')
    op.drop_table('texts')
    op.add_column('files', sa.Column('stored_filename', sa.String(), nullable=False))
    op.add_column('files', sa.Column('file_type', sa.String(), nullable=False))
    op.add_column('files', sa.Column('file_path', sa.String(), nullable=False))
    op.alter_column('files', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('files', 'filepath')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('filepath', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('files', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('files', 'file_path')
    op.drop_column('files', 'file_type')
    op.drop_column('files', 'stored_filename')
    op.create_table('texts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('texts_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('texts_pkey'))
    )
    op.create_index(op.f('ix_texts_id'), 'texts', ['id'], unique=False)
    # ### end Alembic commands ###
